set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TOOLCHAIN_PREFIX arm-rockchip830-linux-uclibcgnueabihf)

if(DEFINED ENV{TOOLCHAIN_PATH})
    set(TOOLCHAIN_PATH "$ENV{TOOLCHAIN_PATH}")
elseif(DEFINED ENV{LUCKFOX_SDK})
    set(TOOLCHAIN_PATH "$ENV{LUCKFOX_SDK}/tools/linux/toolchain/${TOOLCHAIN_PREFIX}")
else()
    set(TOOLCHAIN_PATH "/toolchain")
endif()

set(CMAKE_C_COMPILER   "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-gcc")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-g++")
set(CMAKE_SYSROOT      "${TOOLCHAIN_PATH}/${TOOLCHAIN_PREFIX}/sysroot")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_C_FLAGS   "-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard -O2" CACHE STRING "")
set(CMAKE_EXE_LINKER_FLAGS "-Wl,--gc-sections" CACHE STRING "")
